# host_vars/vettabase-ansible-galera3.yml

---

# MariaDB Host
var_host_mariadb:
  - { name: 'server_id', value: 17210123 }

# Galera Host
var_host_galera:
  - { name: 'wsrep_node_name', value: 'ansible-galera3' }
  - { name: 'wsrep_node_address', value: '172.10.1.23' }
  - { name: 'wsrep_cluster_address', value: 'gcomm://172.10.1.21,172.10.1.22,172.10.1.23' }